sudo: false

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.2.0.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-9.2.0.0
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - yes | gem update --system --force
  - gem install bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: bundle exec rspec --tag ~performance:true

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache: bundler

env:
  global:
    CC_TEST_REPORTER_ID=99325a42b78ef51a9d51574d20dbcd6acdfe75c8568f1433f73b61f17149e05d
    COVERAGE=1
